import img1 from '../../../assets/discover1.png'
export const GalleryData = [
    {
        id:1,
        titile:"Art",
        image:"https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg"
    },
    {
        id:2,
        titile:"Art",
        image:"../../../assets/collection-3.png"
    },
    {
        id:3,
        titile:"Art",
        image:{img1}
    },
    {
        id:4,
        titile:"Art",
        image:"../../../assets/discover1.png"
    },
    {
        id:5,
        titile:"Celebrities",
        image:"../../../assets/discover1.png"
    },
    {
        id:6,
        titile:"Celebrities",
        image:"../../../assets/discover1.png"
    },
    {
        id:7,
        titile:"Celebrities",
        image:"../../../assets/discover1.png"
    },
    {
        id:8,
        titile:"Gaming",
        image:"../../../assets/discover1.png"
    },


    {
        id:9,
        titile:"Gaming",
        image:"../../../assets/discover1.png"
    },
    {
        id:10,
        titile:"Sport",
        image:"../../../assets/discover1.png"
    },
    {
        id:11,
        titile:"Sport",
        image:"../../../assets/discover1.png"
    },
    {
        id:12,
        titile:"Sport",
        image:"../../../assets/discover1.png"
    },
    {
        id:13,
        titile:"Sport",
        image:"../../../assets/discover1.png"
    },
    {
        id:14,
        titile:"Music",
        image:"../../../assets/discover1.png"
    },
    {
        id:15,
        titile:"Music",
        image:"../../../assets/discover1.png"
    },
    {
        id:16,
        titile:"Crypto",
        image:"../../../assets/discover1.png"
    },
]